// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../src/parallel/events/event-listener.js', ['parallel.events.EventListener'], [], false);
goog.addDependency('../../../src/parallel/events/event.js', ['parallel.events.Event'], ['parallel.events.EventListener'], false);
goog.addDependency('../../../src/parallel/shared/array.js', ['parallel.shared.Array'], ['parallel.shared.SharedObject'], false);
goog.addDependency('../../../src/parallel/shared/object-proxy.js', ['parallel.shared.ObjectProxy'], [], false);
goog.addDependency('../../../src/parallel/shared/shared-object.js', ['parallel.shared.SharedObject'], [], false);
goog.addDependency('../../../src/parallel/thread-message.js', ['parallel.ThreadMessage'], [], false);
goog.addDependency('../../../src/parallel/thread-pool.js', ['parallel.ThreadPool'], ['parallel.ObjectProxy', 'parallel.ThreadProxy'], false);
goog.addDependency('../../../src/parallel/thread-proxy.js', ['parallel.ThreadProxy'], ['goog.async.Deferred', 'parallel.ThreadMessage', 'parallel.events.Event', 'parallel.shared.ObjectProxy', 'utils'], false);
goog.addDependency('../../../src/parallel/thread.js', ['parallel.Thread'], ['parallel.ThreadMessage', 'parallel.shared.Array', 'parallel.shared.ObjectProxy', 'utils'], false);
goog.addDependency('../../../src/utils/utils.js', ['utils'], [], false);
